More refactoring and added integration tests for different auth types

diff --git a/.github/workflows/test_azure_devtest_labs_integration.yml b/.github/workflows/test_azure_devtest_labs_integration.yml
--- a/.github/workflows/test_azure_devtest_labs_integration.yml
+++ b/.github/workflows/test_azure_devtest_labs_integration.yml
@@ -18,6 +18,7 @@ on:
 jobs:
   # This workflow contains a single job called "build"
   build-and-integration-test:
+    name: Build and run tests on Azure DevTest Labs
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
 
@@ -53,7 +54,7 @@ jobs:
     #     ls -ltAR ./${{ env.FUNCTIONS_PROJECT_NAME }}/bin/${{ env.BUILD_CONFIGURATION }}
 
     - name: Run Unit Tests
-      run: dotnet test --no-build --configuration ${{ env.BUILD_CONFIGURATION }} --filter TestCategory=UnitTest --output ./output --verbosity normal
+      run: dotnet test --no-build --configuration ${{ env.BUILD_CONFIGURATION }} --filter TestCategory=UnitTest --output ./output --results-directory ./test-results --verbosity normal --logger "trx;LogFileName=unit-test-results.trx"
 
 
     # Login to Azure
@@ -134,8 +135,16 @@ jobs:
 
 
     - name: Run Integration Tests
-      run: dotnet test --no-build --configuration ${{ env.BUILD_CONFIGURATION }} --filter TestCategory=IntegrationTest --output ./output --verbosity normal --settings ${{ env.RUN_SETTINGS_FILENAME }}
+      run: dotnet test --no-build --configuration ${{ env.BUILD_CONFIGURATION }} --filter TestCategory=IntegrationTest --output ./output --results-directory ./test-results --verbosity normal --logger "trx;LogFileName=integration-test-results.trx" --settings ${{ env.RUN_SETTINGS_FILENAME }}
 
 
+
+    - name: Publish Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: Tests                 # Name of the check run which will be created
+        path: ./test-results/*.trx                 # Path to test results
+        reporter: dotnet-trx        # Format of test results
 
     
